### ISSUE TITLE
Make basm-rs great again

### ISSUE THREAD

**Issue by simnalamburt** [kiwiyou/basm-rs#96]
MBGA

### TODOs
- [ ] Put some cute logo to README (something like https://github.com/SAWARATSUKI/KawaiiLogos/blob/main/Go%20Lang/Golang.png)
- [ ] Host a rustdoc website (hopefully docs.rs)
- [ ] Buy basm.rs domain
- [ ] Create a branding website (대충 https://bun.sh/ 이런느낌으로)
- [ ] else?

**Comment by greenstar1151** [comment]
로고를 만들었습니다. https://github.com/kiwiyou/basm-rs/pull/101 

Make basm-rs Great Again!

**Comment by simnalamburt** [comment]
Made a new github org https://github.com/boj-rs, and invited @kiwiyou and @byeongkeunahn as owners

**Comment by byeongkeunahn** [comment]
Whoa, I needed to setup 2FA on my phone for the first time to accept the invitation ;-)
Do you have some kind of plans on what to do?

**Comment by simnalamburt** [comment]
I've also invited @Bubbler-4, who is creater of [cargo-boj](https://github.com/Bubbler-4/cargo-boj) and [gaboja](https://github.com/Bubbler-4/gaboja). I am trying to gather Rust projects related to Baekjoon, such as basm and gaboja, in one place so that they can promote each other and create synergy. If everyone agrees to move the basm, gaboja, and cargo-boj projects under the boj.rs organization on GitHub, I plan to purchase the domain https://boj.rs and run a project introduction page.

**Comment by byeongkeunahn** [comment]
Since migration is completed, we need to fix the URL in the templates to point to the new repo.

**Comment by kiwiyou** [comment]
@byeongkeunahn The codespace link in README has been fixed. https://github.com/boj-rs/basm-rs/commit/136c164bfb78875fb2eb1f8a53e6308468c16453

**Comment by byeongkeunahn** [comment]
@kiwiyou Nice. Could you also update the templates in scripts/templates?

**Comment by byeongkeunahn** [comment]
It seems like the codespaces prebuild isn't working after the transfer. 
> For repositories owned by organizations, repository-level settings for GitHub Codespaces are available for organizations on GitHub Team and GitHub Enterprise plans. To access the settings, the organization or its parent enterprise must have added a payment method and set a spending limit for GitHub Codespaces.

I believe this can be a blocker for maintaining basm-rs repo under this organization account. How should we deal with this?

**Comment by byeongkeunahn** [comment]
I've implemented a workaround. The link to Codespaces is fixed to my repo, where prebuild runs normally without billing. The downside is that it must be kept sync with the main repo. Tell me if it goes stale.
